name: build
on:
  pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@444c9db6fa75e2d9c19ebf1fde7322089be9009e # master
        with:
          directory: terraform/
