on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
    - uses: returntocorp/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
